### ISSUE TITLE
Hide scrollbar on image slider

### ISSUE THREAD

**Issue by ketanmistry** [ketanmistry/taillour-theme#26]
Should be able to simplify the existing CSS with the following example:

```css
.element::-webkit-scrollbar {
  display: none;
}
```

Also add the following to the slider items:

```css
.slider-item {
  scroll-snap-align: center;
}
```
